export { default as MainPage } from './MainPage';
export { default as DetailPage } from './DetailPage';
export { default as ChatPage } from './ChatPage';
export { default as LoginPage } from './LoginPage';
export { default as SignupPage } from './SignupPage';
export { default as AboutPage } from './AboutPage';
export { default as Mypage } from './MyPage';
export { default as PostWritePage } from './PostWritePage';
export { default as KakaoCallbackPage } from './KakaoCallbackPage';
